name 'kbe_login_banner'
maintainer 'Kyle Evans'
maintainer_email 'kylebe@gmail.com'
license 'all_rights'
description 'Installs/Configures kbe_login_banner'
long_description 'Installs/Configures kbe_login_banner'
version '0.1.0'
